version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  assignees:
  - larsgrefer
  ignore:
  - dependency-name: com.android.tools.build:gradle
    versions:
    - 4.1.2
